AWSTemplateFormatVersion: 2010-09-09
Description: Creates the chat ws gateway
Resources: 
  ChatWS:
    Type: 'AWS::ApiGatewayV2::Api'
    Properties:
      Name: ChatWS
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action
      ApiKeySelectionExpression: $request.header.x-api-key
  NewMessageRoute:
    Type: 'AWS::ApiGatewayV2::Route'
    Properties:
      ApiId: !Ref ChatWS
      RouteKey: newmessage
      AuthorizationType: NONE
      Target: !Join 
        - /
        - - integrations
          - !Ref NewMessageIntegration
  NewMessageIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ChatWS
      Description: New Message Integration
      IntegrationType: HTTP
      IntegrationUri: http://localhost:5000/api/messages